# Generated by Django 5.0.4 on 2025-01-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject_question_subject_unique_subject_per_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('9am-10am', '9am-10am'), ('10am-11am', '10am-11am'), ('11am-11:15am', '11am-11:15am (Short Break)'), ('11:15am-12:15pm', '11:15am-12:15pm'), ('12:15pm-1:15pm', '12:15pm-1:15pm'), ('1:15pm-1:45pm', '1:15pm-1:45pm (Lunch Break)'), ('1:45pm-2:45pm', '1:45pm-2:45pm'), ('2:45pm-3:45pm', '2:45pm-3:45pm'), ('3:45pm-4:45pm', '3:45pm-4:45pm'), ('4:45pm-5:45pm', '4:45pm-5:45pm')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
