# Generated by Django 5.0.4 on 2025-01-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='time_slot',
            field=models.CharField(choices=[('9am-10am', '9am-10am'), ('10am-11am', '10am-11am'), ('11:15am-12:15pm', '11:15am-12:15pm'), ('12:15pm-1:15pm', '12:15pm-1:15pm'), ('1:45pm-2:45pm', '1:45pm-2:45pm'), ('2:45pm-3:45pm', '2:45pm-3:45pm'), ('3:45pm-4:45pm', '3:45pm-4:45pm'), ('4:45pm-5:45pm', '4:45pm-5:45pm')], max_length=20),
        ),
    ]
