# Generated by Django 5.0.4 on 2025-02-14 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_quiz_quizquestion_studentattempt_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattempt',
            name='date_attempted',
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='division',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='roll_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='total_time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
