# Generated by Django 5.0.4 on 2025-03-06 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_plagiarismreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper_name', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('exam_type', models.CharField(max_length=50)),
                ('exam_time', models.TimeField()),
                ('exam_date', models.DateField()),
                ('question_paper_file', models.FileField(upload_to='question_papers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_papers', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='main.subject')),
            ],
            options={
                'verbose_name': 'Question Paper',
                'verbose_name_plural': 'Question Papers',
            },
        ),
    ]
